[profile.default]
src = "src"
out = "out"
libs = ["lib", "node_modules"]


# Network configurations - RPC endpoints for all supported chains
[rpc_endpoints]
sepolia = "https://sepolia.infura.io/v3/${INFURA_API_KEY}"
ethSepolia = "https://sepolia.infura.io/v3/${INFURA_API_KEY}"
baseSepolia = "https://base-sepolia.infura.io/v3/${INFURA_API_KEY}"
arbitrumSepolia = "https://arbitrum-sepolia.infura.io/v3/${INFURA_API_KEY}"

# Etherscan API keys for verification
[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api-sepolia.etherscan.io/api" }
ethSepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api-sepolia.etherscan.io/api" }
baseSepolia = { key = "${BASESCAN_API_KEY}", url = "https://api-sepolia.basescan.org/api" }
arbitrumSepolia = { key = "${ARBISCAN_API_KEY}", url = "https://api-sepolia.arbiscan.io/api" }


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
